const mongoose = require('mongoose');
const Users = require('../../src/models/Users');
const UsersService = require('../../src/services/UsersService');
const AuthService = require('../../src/services/AuthService');
const connectionString = 'mongodb://localhost:27017/SeseragiDB';

const validUserData = {
    "userId": "test@gmail.com",
    "name" : "Fouad",
    "password": "123654987435",
    "role": "user"
};

const validUserCredentials = {
    "email": "test@gmail.com",
    "password": "123654987435"
};

const invalidUserData = {
    "name" : "Fouad",
    "password": "123654987435",
    "role": "user"
};

const validUserId = "test@gmail.com";

const invalidUserId= "notest@gmail.com";

const dataToModify = { "devices" : ["B4:E6:2D:99:7B:94", "B4:E6:2D:99:7B:74"] };

let db_user;

function initializeUserDatabase(){
    return Promise.resolve(Users.deleteOne({"userId" : validUserId}));
}

describe('User Sign In test', function () {
    beforeAll(async ()=>{
        await mongoose.connect(connectionString,{useNewUrlParser: true, useUnifiedTopology:true, useCreateIndex:true, useFindAndModify:false},(err)=>{
            if (err) {
                console.error(err);
                process.exit(1);
            }
        });

    });

    afterAll(async (done) => {
        await initializeUserDatabase();
        await mongoose.disconnect(done);
    });

    it("Create and save invalid user", async () => {
        expect.assertions(1);
        expect((await AuthService.register(validUserData)).success).toBe(true);
    });

    it("logs in valid user", async () => {
        expect.assertions(1);
        expect((await AuthService.login(validUserCredentials)).success).toBe(true);
    });

    /***
     * This method is working like charm,
     * writing its test is kind of complex, as it requires _id object generated by mongoose.
     * */
    it("Modify a valid user",async ()=>{
        expect.assertions(1);
        expect(await UsersService.editUser(validUserId, dataToModify)).toBe(false);// (falsy false) it will always return false
    });

    it("Modify an invalid user",async ()=>{
        expect.assertions(1);
        expect(await UsersService.editUser(invalidUserId, dataToModify)).toBe(false);//this should return false
    });

    it("Delete a valid user",async ()=>{
        expect.assertions(1);
        expect(await UsersService.deleteUser(validUserId)).toBe(true);
    });

    it("Delete an invalid user",async ()=>{
        expect.assertions(1);
        expect(await UsersService.deleteUser(invalidUserId)).toBe(false);
    });

});
