version: '1'
services:
  server:
    container_name: server
    build: https://github.com/fouadmen/seseragi-backend.git
    restart: always
    ports:
      - '80:9000'
    links:
      - mongo
    command: npm start
  db:
    container_name: db
    image: mongo
    ports:
      - '27017:27017'
