version: '3.3'
services:
  server:
    container_name: server
    build: https://github.com/fouadmen/seseragi-backend.git
    restart: always
    ports:
      - '80:9000'
      - '1883:1883'
    links:
      - mongo
    command: npm start
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

